updates

diff --git a/installOSXroot b/installOSXroot
--- a/installOSXroot
+++ b/installOSXroot
@@ -10,19 +10,11 @@ if [[ $? != 0 ]] ; then
     echo "install root correctly"
 
 else
+    brew install root
+    if [[ $? != 0 ]] ; then
 
-    echo "Installing ROOT"
-
-    cd
-    mkdir Software
-    cd Software
-    mkdir root_build root_install
-    git clone --branch latest-stable https://github.com/root-project/root.git root_src
-    cd root_build
-    cmake -DCMAKE_INSTALL_PREFIX=../root_install -Dbuiltin_glew=ON ../root_src
-
-    echo "Compiling ROOT. It will take a while..."
-
-    cmake --build . -- install -j4
+        echo " ------ "
+        echo "'root' failed to install: see installation output" 
+    fi
 fi
 
